import type { Metadata } from "next";
import { Lato, Poppins } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./ApolloWrapper";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/Footer";
import { query } from "@/lib/apollo-client";
import { GetCategoriesQuery } from "@/lib/queries";
import { AuthProvider } from "./components/providers/AuthProvider";

const poppins = Poppins({
  weight: ["300", "500"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categoriesQuery = await query({
    query: GetCategoriesQuery,
  });

  return (
    <html lang="en" className={`${poppins.variable} ${lato.variable}`}>
      <body>
        <ApolloWrapper>
          <AuthProvider>
            <Navbar categories={categoriesQuery.data.metadata.categories} />
            <div className="pt-32 lg:pt-36">{children}</div>
            <Footer categories={categoriesQuery.data.metadata.categories} />
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
