"use client";

// pages/index.tsx
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  return (
    <div>
      <Head>
        <title>My E-commerce Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header with Navigation and Search Bar */}
      <header className="bg-white shadow">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center">
            <img src="/logo.png" alt="Logo" className="h-10 mr-4" />
            <h1 className="text-2xl font-bold">My E-commerce Site</h1>
          </div>
          <div className="flex items-center">
            <nav className="hidden md:flex space-x-4 mr-4">
              <a href="#" className="text-gray-600 hover:text-gray-900">
                Home
              </a>
              <a href="#" className="text-gray-600 hover:text-gray-900">
                Products
              </a>
              <a href="#" className="text-gray-600 hover:text-gray-900">
                About
              </a>
              <a href="#" className="text-gray-600 hover:text-gray-900">
                Contact
              </a>
            </nav>
            <div className="relative">
              <input
                type="text"
                className="border rounded-full py-2 px-4"
                placeholder="Search products..."
              />
              <button className="absolute right-2 top-2 text-gray-600">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-5 h-5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 21l-4.35-4.35m1.75-5.4a7.5 7.5 0 11-15 0 7.5 7.5 0 0115 0z"
                  />
                </svg>
              </button>
            </div>
            <button className="ml-4">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-6 h-6 text-gray-600"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M3 3h18v18H3V3z"
                />
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M7 10.5a2.5 2.5 0 015 0 2.5 2.5 0 015 0m-10 2h10"
                />
              </svg>
            </button>
            {isLoggedIn ? (
              <div className="ml-4 text-gray-600">Account Info</div>
            ) : (
              <div className="ml-4">
                <button className="text-gray-600 hover:text-gray-900 mr-2">
                  Login
                </button>
                <button className="text-gray-600 hover:text-gray-900">
                  Register
                </button>
              </div>
            )}
          </div>
        </div>
      </header>

      {/* Navigation Bar for Product Categories */}
      <nav className="bg-gray-100 shadow-inner py-2">
        <div className="container mx-auto px-4 flex space-x-4 overflow-x-auto">
          {[
            "Fruits",
            "Vegetables",
            "Dairy",
            "Meat",
            "Seafood",
            "Beverages",
            "Bakery",
          ].map((category) => (
            <div className="group relative" key={category}>
              <a href="#" className="text-gray-600 hover:text-gray-900">
                {category}
              </a>
              <div className="absolute hidden group-hover:block bg-white shadow-lg mt-2 rounded-lg p-4 w-64">
                <h4 className="font-bold mb-2">{category}</h4>
                <div className="grid grid-cols-1 gap-2">
                  <div className="flex items-center">
                    <div className="w-16 h-16 bg-gray-200 mr-2"></div>
                    <div>Subcategory 1</div>
                  </div>
                  <div className="flex items-center">
                    <div className="w-16 h-16 bg-gray-200 mr-2"></div>
                    <div>Subcategory 2</div>
                  </div>
                  <div className="flex items-center">
                    <div className="w-16 h-16 bg-gray-200 mr-2"></div>
                    <div>Subcategory 3</div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </nav>

      <main className="container mx-auto px-4 py-8">
        {/* Main Banner */}
        <section className="bg-gray-300 h-64 mb-8 flex items-center justify-center">
          <h2 className="text-4xl font-bold text-white">Main Banner</h2>
        </section>

        {/* Product Categories Section */}
        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4">Product Categories</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-gray-200 h-40 flex items-center justify-center">
              Category 1
            </div>
            <div className="bg-gray-200 h-40 flex items-center justify-center">
              Category 2
            </div>
            <div className="bg-gray-200 h-40 flex items-center justify-center">
              Category 3
            </div>
            <div className="bg-gray-200 h-40 flex items-center justify-center">
              Category 4
            </div>
          </div>
        </section>

        {/* Featured Products Section */}
        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-4 text-center">
            Featured Products
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-gray-200 h-40 flex flex-col items-center justify-center p-4">
              <div className="bg-gray-400 h-20 w-full mb-2"></div>
              <h3 className="text-lg font-bold">Product 1</h3>
              <p className="text-gray-600">$19.99</p>
            </div>
            <div className="bg-gray-200 h-40 flex flex-col items-center justify-center p-4">
              <div className="bg-gray-400 h-20 w-full mb-2"></div>
              <h3 className="text-lg font-bold">Product 2</h3>
              <p className="text-gray-600">$29.99</p>
            </div>
            <div className="bg-gray-200 h-40 flex flex-col items-center justify-center p-4">
              <div className="bg-gray-400 h-20 w-full mb-2"></div>
              <h3 className="text-lg font-bold">Product 3</h3>
              <p className="text-gray-600">$39.99</p>
            </div>
            <div className="bg-gray-200 h-40 flex flex-col items-center justify-center p-4">
              <div className="bg-gray-400 h-20 w-full mb-2"></div>
              <h3 className="text-lg font-bold">Product 4</h3>
              <p className="text-gray-600">$49.99</p>
            </div>
          </div>
        </section>

        {/* Promotional Banners */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-8">
          <div className="bg-gray-300 h-40 flex items-center justify-center">
            <h2 className="text-2xl font-bold text-white">Promo Banner 1</h2>
          </div>
          <div className="bg-gray-300 h-40 flex items-center justify-center">
            <h2 className="text-2xl font-bold text-white">Promo Banner 2</h2>
          </div>
        </section>
      </main>

      <footer className="bg-gray-800 text-white py-8">
        <div className="container mx-auto px-4 grid grid-cols-1 md:grid-cols-4 gap-8">
          <div>
            <h3 className="font-bold mb-4">About Us</h3>
            <p>Learn more about our company and values.</p>
          </div>
          <div>
            <h3 className="font-bold mb-4">Customer Service</h3>
            <ul>
              <li>
                <a href="#" className="text-gray-400 hover:text-white">
                  Contact Us
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-400 hover:text-white">
                  FAQ
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-400 hover:text-white">
                  Shipping & Returns
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold mb-4">Follow Us</h3>
            <ul>
              <li>
                <a href="#" className="text-gray-400 hover:text-white">
                  Facebook
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-400 hover:text-white">
                  Instagram
                </a>
              </li>
              <li>
                <a href="#" className="text-gray-400 hover:text-white">
                  Twitter
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold mb-4">Subscribe</h3>
            <p>Get the latest updates and offers.</p>
            <div className="mt-2">
              <input
                type="email"
                className="w-full px-2 py-1 rounded"
                placeholder="Enter your email"
              />
              <button className="w-full mt-2 bg-blue-500 text-white py-1 rounded">
                Subscribe
              </button>
            </div>
          </div>
        </div>
        <div className="text-center mt-8">
          <p>&copy; 2024 My E-commerce Site. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
